### ISSUE TITLE
rootfs optimisation breaks compatibility

### ISSUE THREAD

**Issue by mtekel** [cloudfoundry/cflinuxfs3-release#11]
Hello,

looks like the disk space usage optimisation made in https://github.com/cloudfoundry/cflinuxfs3-release/pull/4 breaks compatibility with older CF releases. Older versions of CF/diego/garden do expect to find the folder and if is not present, garden will fail to create container. Because of this, the latest version we can use is v0.94.0, which had this optimisation removed.

cf/259.2, diego/1.15.0, garden-runc/1.6.0
```
{"timestamp":"1587559910.057500839","source":"guardian","message":"guardian.create.create-failed-cleaningup.volume-creator.destroy.finished","log_level":1,"data":{"cause":"repository_fetcher: stat file: lstat /var/vcap/packages/cflinuxfs3/rootfs: no such file or directory","handle":"5f05ef25-c0d8-45c4-b663-317216ec8e86","id":"5f05ef25-c0d8-45c4-b663-317216ec8e86","session":"32.3.2.1"}}
```

It would be nice if older platforms could also use cflinuxfs3. It looks like the fix is to just remove the last line of pre-start job (https://github.com/cloudfoundry/cflinuxfs3-release/blob/3d0505094a5cb84b763780d62e93c8a334c05cc8/jobs/cflinuxfs3-rootfs-setup/templates/pre-start#L50).

**Comment by martyspiewak** [comment]
@emalm cleaning up old cf issues, do you know if this is still relevant for compatibility with recent enough cf versions?

**Comment by emalm** [comment]
I would guess not, but if the error message is coming from Garden then I'd expect the @cloudfoundry/cf-garden team to have an authoritative answer. @aminjam or @sunjayBhatia might also have some informative technical context.

**Comment by sunjayBhatia** [comment]
I would defer to the Garden team but I'm guessing those old versions are not supported and definitely not tested with newer rootFS releases so no one is validating their compatibility.

**Comment by kieron-dev** [comment]
The error message comes from garden-shed, which predates my time on the garden team. The [line](https://github.com/cloudfoundry-attic/garden-shed/blame/3c13c8da220fb1dae6fa3cb2e77a48355103a968/repository_fetcher/local.go#L91) was last touched in 2015 :)

It looks like the [request for the rootfs dir](https://github.com/cloudfoundry/guardian/blob/cf6012a27dbf5646062a9a83f8c95d12a65c9856/gardener/gardener.go#L229-L253) comes from the container spec.Image.URI, which must be constructed in diego.

So I think it's a matter of making the diego container create spec consistent with what's on the cell filesystem, one way or the other.

**Comment by sunjayBhatia** [comment]
We started using the `rootfs.tar` path when we switched to GrootFS in CF: https://github.com/cloudfoundry/cf-deployment/commit/461e822d0a04653daf55b48e6b46370700d7f6f0 (but maybe I should have checked on garden shed compatibility before removing the line in question). Given that old version of CF is probably unsupported (https://github.com/cloudfoundry-attic/cf-release/releases/tag/v259) and we don't have plans to test/validate with garden shed I would say to close this with "wontfix" and suggest upgrading to more modern versions of the components in question.
