### ISSUE TITLE
Incorrect repo description?

### ISSUE THREAD

**Issue by reupen** [cloudfoundry/cflinuxfs3-release#3]
The description for this repo says 'This is a work in progress, you should still be using cflinuxfs2' here:

![image](https://user-images.githubusercontent.com/12693549/50967265-87c2ff00-14cf-11e9-8210-c386434e47b8.png)

At the same time, https://docs.cloudfoundry.org/devguide/deploy-apps/stacks.html says to migrate to cflinuxfs3.

I assume the repo description is just out of date?

**Comment by sclevine** [comment]
You are correct -- the description is out-of-date. Updating it right now 😄
