### ISSUE TITLE
cflinuxfs3-rootfs-setup pre-start is not idempotent

### ISSUE THREAD

**Issue by fhambrec** [cloudfoundry/cflinuxfs3-release#5]
Hi,

we have just noticed that the `pre-start` script of the `cflinuxfs3-rootfs-setup` job is not idempotent. It can happen under certain circumstances that BOSH runs the script twice which leads to the following error:
```
 CONF_DIR=/var/vcap/jobs/cflinuxfs3-rootfs-setup/config
+ ROOTFS_PACKAGE=/var/vcap/packages/cflinuxfs3
+ ROOTFS_DIR=/var/vcap/packages/cflinuxfs3/rootfs
+ ROOTFS_TAR=/var/vcap/packages/cflinuxfs3/rootfs.tar
+ TRUSTED_CERT_FILE=/var/vcap/jobs/cflinuxfs3-rootfs-setup/config/certs/trusted_ca.crt
+ CA_DIR=/var/vcap/packages/cflinuxfs3/rootfs/usr/local/share/ca-certificates/
+ '[' '!' -d /var/vcap/packages/cflinuxfs3/rootfs ']'
+ grep -q trusted_ca_certificates /var/vcap/jobs/cflinuxfs3-rootfs-setup/config/certs/trusted_ca.crt
grep: /var/vcap/jobs/cflinuxfs3-rootfs-setup/config/certs/trusted_ca.crt: No such file or directory
+ rm -f /var/vcap/packages/cflinuxfs3/rootfs/usr/local/share/ca-certificates/trusted-ca-1.crt /var/vcap/packages/cflinuxfs3/rootfs/usr/local/share/ca-certificates/trusted-ca-2.crt /var/vcap/packages/cflinuxfs3/rootfs/usr/local/share/ca-certificates/trusted-ca-3.crt
+ mkdir -p /var/vcap/packages/cflinuxfs3/rootfs/usr/local/share/ca-certificates/
+ /var/vcap/packages/rootfs-certsplitter/bin/certsplitter /var/vcap/jobs/cflinuxfs3-rootfs-setup/config/certs/trusted_ca.crt /var/vcap/packages/cflinuxfs3/rootfs/usr/local/share/ca-certificates/
2019/04/10 12:20:25 open /var/vcap/jobs/cflinuxfs3-rootfs-setup/config/certs/trusted_ca.crt: no such file or directory
```
This happens because after the first run the `trusted_ca.crt` file is missing. Subsequently the if condition will not be executed and the $TRUSTED_CERT_FILE will not change to `trusted_ca.json`.

Can you please check?

Thanks for your support.

**Comment by philippthun** [comment]
As this issue happened several times, we forked `cflinuxfs3-release` and simply replaced `move` with `copy` [here](https://github.com/cloudfoundry/cflinuxfs3-release/blob/7fd72554dfda0605a0e0d24d969574346dd10d0a/jobs/cflinuxfs3-rootfs-setup/templates/pre-start#L18). This makes the script idempotent.

**Comment by dwillist** [comment]
@fhambrec @philippthun thanks for the troubleshooting. We'll prioritize this ASAP.

**Comment by tlwr** [comment]
@philippthun thanks for your fix

**Comment by richardTowers** [comment]
I've raised PR #7 with @philippthun's change - GOV.UK PaaS will be deploying a fork with that change until this is fixed upstream.

**Comment by JamesClonk** [comment]
When can a release with a fixed version be expected for this issue?
We are currently also facing very often failed deployments due to the pre-start script failing. It has become a major hassle to manually log in and "fix" cell vm's during every cf deployment for us.
A timeline for this would be appreciated.

**Comment by zmackie** [comment]
#7 Was merged a while back. Closing.
